language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- npm install netlify-cli@next -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book --draft
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
  - provider: script
    script: netlify deploy --dir _book --prod
    skip_cleanup: true
    on:
      branch: master
