language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- npm install netlify-cli@next -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: script
  script: netlify deploy --prod
  skip_cleanup: true
